version: '3.8'

services:
  app:
    build: .
    container_name: rec-ledger-app
    restart: unless-stopped
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
      - PORT=5000
      - DOMAIN=rec-ledger.com
      - DATABASE_URL=${DATABASE_URL}
      - SESSION_SECRET=${SESSION_SECRET}
    volumes:
      - ./logs:/app/logs
      - ./ssl:/app/ssl
      - ./uploads:/app/uploads
    depends_on:
      - db
    networks:
      - rec-ledger-network

  db:
    image: postgres:15-alpine
    container_name: rec-ledger-db
    restart: unless-stopped
    environment:
      - POSTGRES_DB=rec_ledger
      - POSTGRES_USER=rec_ledger_user
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./backups:/backups
    ports:
      - "5432:5432"
    networks:
      - rec-ledger-network

  nginx:
    image: nginx:alpine
    container_name: rec-ledger-nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./ssl:/etc/ssl/certs
      - /var/log/nginx:/var/log/nginx
    depends_on:
      - app
    networks:
      - rec-ledger-network

volumes:
  postgres_data:

networks:
  rec-ledger-network:
    driver: bridge